spring.application.name=BT8_LTWeb
server.port=8080

# Databse SQL Server Configuration (Chỉnh lại tên DB, username/password phù hợp máy bạn)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BT8_GraphQL_DB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# GraphQL & GraphiQL Console Config
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.cors.allowed-origins=*