spring.application.name=BT8_LTWeb
server.port=8080

# Cấu hình UTF-8 Encoding cho Web Servlet
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# Database SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BT8_GraphQL_DB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate Config
# Đổi thành 'create' cho lần chạy này để cập nhật cột VARCHAR -> NVARCHAR trong DB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# GraphQL & GraphiQL Console Config
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.cors.allowed-origins=*